### ISSUE TITLE
fresh install unbound use 600 MB Ram

### ISSUE THREAD

**Issue by Saugjunkie** [complexorganizations/unbound-manager#49]
Hello what is with unbound after a fresh install? He used 600 Mb Ram and zero CPU is this about the host file in /etc/unbound?

**Comment by ghost** [comment]
Hello,
When unbound reads the local block list, it uses a lot of memory at first, then gradually uses less.
- prajwal

**Comment by Saugjunkie** [comment]
i dont no what is wrong at the moment with unbound? I think he use to much ressourcen i have simulan whatch the same video on youtube. The Laptop with home internt looks at 1080p60 und the cellphone with mobile internet in 2160p60. 

The CPU sometimes goes over 90%. 

The same Server but i have installed 3 days befor the sam video and connection totaly smooth with 9 - 12% use.

What can i see is, every the CPU goes up comes this 
/usr/sbin/haveged --foreground --verbose = 1 -w 1024 but htop says it use 0,5 or 1,0% CPU when the code is finisch and go out the list CPU usage goes down

that i have not on the another server he works smoothly

**Comment by ghost** [comment]
Hey,
Make sure you have installed https://github.com/gorhill/uBlock on your laptop.

**Comment by Saugjunkie** [comment]
i mean the cpu usage on the server not on my laptop

**Comment by ghost** [comment]
Give me time, i will optimize it more.

**Comment by Saugjunkie** [comment]
> 
> 
> Give me time, i will optimize it more.

of course, you have all the time you want. 
I only testing wat you give us and than  give feedback, in my really verry bad english

**Comment by ghost** [comment]
Hey, unbound is using way too much memory, gonna change it to coredns.

**Comment by Saugjunkie** [comment]
so this project is death and start new projekt with coredns? ok what ever you thing is the best

**Comment by ghost** [comment]
Yes.
I looked at the unbound source code, and it's not something I'd utilize in 2021.
